# Generated by Django 2.2 on 2019-05-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='las_modified',
            new_name='last_modified',
        ),
    ]
